id: IA7F71729
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:52:19.520448'
last_modified: '2022-06-18T23:52:19.520464'
parser: null
source_metadata:
  title: Sa paṇs Treatise on Music and Ji ltar dri tshul, block print, colophon excerpt
  author: ས་སྐྱ་པཎྜི་ཏ་ཀུན་དགའ་རྒྱལ་མཚན།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2015-07-14);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:David Jackson (dj), Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/938
  bases:
    3da9:
      title: Sa paṇs Treatise on Music and Ji ltar dri tshul, block print, colophon
        excerpt
      order: 1
      base_file: 3da9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
